global:
  scrape_interval: 15s 
  evaluation_interval: 15s
  scrape_timeout: 10s

  external_labels:
    monitor: 'prometheus-monitor'

scrape_configs:

  - job_name: 'rencie'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['rencie:8000']