services:
  renciapi:
    container_name: renci
    # build:
    #   context: .
    #   dockerfile: agent.dockerfile
    image: 518033441890.dkr.ecr.us-east-1.amazonaws.com/agent:latest
    ports:
      - "8000:8000"
    restart: always
    networks:
      - chatai
    env_file:
      - ./all.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`renci.devrayco.name.ng`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=myresolverv1
      - traefik.http.services.portainer.loadbalancer.server.port=8000

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - chatai

  worker:
    container_name: celery
    # build:
    #   context: .
    #   dockerfile: agent.dockerfile
    image: 518033441890.dkr.ecr.us-east-1.amazonaws.com/agent:latest
    command: celery -A renci.config.celery_app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - chatai
    env_file:
      - ./all.env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./setups/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - renciapi
    networks:
      - chatai
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`prometheus.devrayco.name.ng`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=myresolverv1
      - traefik.http.services.portainer.loadbalancer.server.port=9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - chatai
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`grafana-renci.devrayco.name.ng`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=myresolverv1
      - traefik.http.services.portainer.loadbalancer.server.port=3000

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - chatai
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.devrayco.name.ng`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=myresolverv1
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  chatai:
    external: true

volumes:
  portainer_data:
