services:
  renciapi:
    container_name: renci
    build:
      context: .
      dockerfile: agent.dockerfile
    # image: 518033441890.dkr.ecr.us-east-1.amazonaws.com/renci:latest
    ports:
      - "8000:8000"
    restart: always
    networks:
      - chatai
    env_file:
      - ./all.env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - chatai

  worker: 
    # image: 518033441890.dkr.ecr.us-east-1.amazonaws.com/renci:latest
    build:
      context: .
      dockerfile: agent.dockerfile
    container_name: celery
    command: celery -A renci.config.celery_app worker --loglevel=info
    depends_on:
      - redis
    networks:
      - chatai

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./setups/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - chatai
    ports:
      - "9090:9090"
    depends_on:
      - renci

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - chatai
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.devrayco.name.ng`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=thenonsensedev

networks:
  chatai:
    external: true

